### ISSUE TITLE
Get stuck when going into Phoenix Gang hideout

### ISSUE THREAD

**Issue by alarixnia** [2004scape/Server#223]
Ladder down works, ladder back up doesn't

**Comment by Pazaz** [comment]
Thanks - confirmed. Fixed, I'll include it with my next commit.

**Comment by alarixnia** [comment]
Damn that was quick

**Comment by Pazaz** [comment]
Rest of phoenix gang TODO (Shield of Arrav not started), but ladder works so you aren't stuck!
