### ISSUE TITLE
can interact with locs through walls

### ISSUE THREAD

**Issue by howspooky** [2004Scape/Server#58]
![screenshot](https://b2.spooky.me/2023/07/firefox_Ve0bI8hwuU.png
 "screenshot")

clicking this chest with the door closed should result in "I can't reach that!", instead its allowing me to interact

**Comment by Jameskmonger** [comment]
This is possibly related to the failing pathfinder tests in my fork

cc @Pazaz

**Comment by Pazaz** [comment]
Worth retesting after the last commit.
