### ISSUE TITLE
Drawers in Make-over mage's house don't open

### ISSUE THREAD

**Issue by Espionage724** [2004Scape/Server#668]
The Drawers have an Open action but nothing happens (no animation, no chatbox text).

The chatbox text in the screenshot is from Examine

![screenshot-1721173850](https://github.com/user-attachments/assets/cd03daac-9f6f-4ce8-9414-de8e7469311f)

May be all Drawers? Happens to the one in Seers' Village too:

![screenshot-1721510130](https://github.com/user-attachments/assets/c28d4999-f83b-4504-ba58-eea5516668e9)

**Comment by Indio3** [comment]
this was an issue with all non-clue related drawers, fixed: https://github.com/2004Scape/Server/pull/678/commits/06e62e8fc94c8bd202681a59e83655772a0614e7
