### ISSUE TITLE
Music stops playing after a while

### ISSUE THREAD

**Issue by Espionage724** [2004Scape/Server#669]
When using the in-browser client, music stops playing after a while:

- Sometimes it stops looping after a while (choosing a new song and going back to Auto works)
- Sometimes music (possibly all audio) stops working altogether (possibly main menu too); it comes back after a quick page refresh

**Comment by ultraviolet-jordan** [comment]
This is fixed in the next update whenever server pulls client changes in. Thank you for the report!
