### ISSUE TITLE
Character sometimes doesn't face rocks while mining

### ISSUE THREAD

**Issue by Espionage724** [2004Scape/Server#672]
Sometimes when walking up to rocks to mine, my character faces the same direction I was walking and keeps that direction upon mining and continual mining (never rotates towards the rock)

On OSRS I recall sometimes having the mining animation start facing the walking direction if I was running to it, and then the character would rotate towards the rock upon mining it.

![screenshot-1721268509](https://github.com/user-attachments/assets/201b3195-de7f-4496-9628-84c8a75f5fd9)

Spinning wheel can do it too:

![screenshot-1721509945](https://github.com/user-attachments/assets/26806dc1-a7d0-4c41-abb3-c789aef993d5)

And Ranges, but if I log-out facing that direction and use the Range immediately after log-in my character rotates towards it:

![screenshot-1721538942](https://github.com/user-attachments/assets/f16ae3f8-4e6f-4dfa-81d2-5d2724d1dcbd)

**Comment by thesuddensilent** [comment]
A similar problem has existed in the past, that the character seems to mine when looking in the wrong direction. but often the character turns when the animation loops again or you manage to get the rock into the backpack successfully.
but there is also that? why did it even happen in the first place.

**Comment by ultraviolet-jordan** [comment]
Depends on if there should be a `p_arrivedelay` or not, most things in OSRS do this and most things in 2004 don't. This is probably one of those cases.

Another examples would be a ton of stairs are like this too.

**Comment by tannerdino** [comment]
Osrs mining has `p_arrivedelay`, https://youtu.be/k-44H0qhUWY this video doesnt
