### ISSUE TITLE
Big NPC's can diagonally walk through blocked tiles

### ISSUE THREAD

**Issue by tannerdino** [2004Scape/Server#956]
https://github.com/user-attachments/assets/8f2b8045-4870-4f82-ba7d-9d3969e98cc7

**Comment by ultraviolet-jordan** [comment]
Nice find & good timing as well, I got you fixed with our new and improved pathfinder:

![idk 207](https://github.com/user-attachments/assets/ec11b491-515d-4fa8-8697-b788b6cf218c)

**Comment by tannerdino** [comment]
Wow perfect! Good work
