### ISSUE TITLE
EntityList is leaky

### ISSUE THREAD

**Issue by ultraviolet-jordan** [2004Scape/Server#967]
https://github.com/2004Scape/Server/blob/02b24d3712fa0f6c7b6533947672334fc8e52c4b/src/lostcity/entity/EntityList.ts#L74C1-L80C6

The `set` function stores an `Entity` into the backing array collection.
The `remove` function does not remove possible `Entity` out. This is protected though due to the way the `get` function is implemented.
Because of this, Players & Npcs that are dynamically added into the array are stored in heap forever, keeping all of their referencing as well, so this is never picked up by the GC.

Possible fix includes:
`this[index] = undefined;`. Using array `splice` would change the length of the backed array.

![image](https://github.com/user-attachments/assets/90fa967b-20b3-4515-b5d3-c23ad82d3a5c)
----

This is my memory usage over time on my local computer with the fix in place over the last 8 hours.
The top is the oldest and the bottom is the most recent:
![image](https://github.com/user-attachments/assets/6c3141fb-2648-41af-9bb1-e450b642da0b)

**Comment by Pazaz** [comment]
fixed: https://github.com/2004Scape/Server/commit/8786120909ec697cdee795ac2fdc22153fd6a1bc
