### ISSUE TITLE
Movement bug with clicking pathing entities

### ISSUE THREAD

**Issue by ultraviolet-jordan** [2004Scape/Server#974]
![cocknballs](https://github.com/user-attachments/assets/98f12b2f-c5c3-4c52-abe7-6d9e164e03ed)

- I have confirmed the new pathfinder did not cause this, probably caused by recent changes to moving related code.
- Occurs when using server or client pathfinder.
- Does not seem to occur with Locs or Objs.
- Can confirm this is a new bug.

**Comment by ultraviolet-jordan** [comment]
Confirmed broken as of PR #930

**Comment by tannerdino** [comment]
> Confirmed broken as of PR #930
https://github.com/2004Scape/Server/blob/207848aeb1bcf14aa33b5cb3a25f283dee4653b3/src/lostcity/engine/World.ts#L691 yeah this line. Not sure what the fix would be without breaking following, might test a few things later tonight

**Comment by ultraviolet-jordan** [comment]
> > Confirmed broken as of PR #930
> 
> https://github.com/2004Scape/Server/blob/207848aeb1bcf14aa33b5cb3a25f283dee4653b3/src/lostcity/engine/World.ts#L691
> 
> yeah this line. Not sure what the fix would be without breaking following, might test a few things later tonight

Sounds god lmk if u ned help

**Comment by tannerdino** [comment]
I'm thinking that pathToPathingTarget() in client input is unique to player following, everything else uses pathToTarget()
