### ISSUE TITLE
Inaccurate player routefinder to overlapping target

### ISSUE THREAD

**Issue by tannerdino** [2004Scape/Server#982]
Currently we use osrs's implementation. Early osrs and pre-2007 runescape, players and npc's handled routefinding to overlapping targets, the exact same way: Moving to a random direction

Example 1: May 11, 2006 [video](https://youtu.be/VzOz2FuXn3k&t=106)

https://github.com/user-attachments/assets/2ef2602a-3b01-434a-8975-6b0da619d179

Example 2: June 29, 2007 [video](https://youtu.be/MfYoyM8EVBs?t=78)

https://github.com/user-attachments/assets/08407718-f051-436b-930a-f8b24204fca2

**Comment by ultraviolet-jordan** [comment]
lots of unknowns about this without being able to test on an original osrs server or something but this can be cheaply done with something like this:

![image](https://github.com/user-attachments/assets/be994ee4-0f4c-45ab-b4a1-6254222591b2)
