### ISSUE TITLE
Pre-2006 videos show NPC's only moving cardinally when pathing towards target 

### ISSUE THREAD

**Issue by tannerdino** [2004Scape/Server#997]
- Video example 1 ([source](https://youtu.be/5itKFWuomiM?t=131)): 

https://github.com/user-attachments/assets/26436d0c-5fb3-4275-aa97-3059dc542c9f

- Video example 2 ([source](https://youtu.be/JEpHdipoIk0?t=204)):

https://github.com/user-attachments/assets/13514441-c284-4cbc-a9cf-679ca3adad00

Looks like it moves on the x axis first, until lined up, **or blocked**, with its target. Then it moves on the z axis. No diagonal movement! Though interestingly npcs can still be safespotted diagonally, so perhaps it doesnt always switch the axis if blocked. Hmmmmm

- Video of npc switching axis when hitting a wall ([source](https://youtu.be/5itKFWuomiM?t=37)):

https://github.com/user-attachments/assets/011848ee-7892-48b5-913a-cda2bf96852b

You can see in this video: west is open, move west -> west is blocked by wall, move south -> west is open, move west -> west is blocked by wall, move south. In a sort of zig zag pattern, since the npc is big and the west wall is shaped like this: 

![image](https://github.com/user-attachments/assets/4a5481bb-94c7-4a4a-a83e-732f2971dddb)

- Diagonal safespot:
![image](https://github.com/user-attachments/assets/e4c81c53-d2c6-4b42-8c55-9af1b93384c9)

**Comment by ultraviolet-jordan** [comment]
Not gonna be easy to pull off with basically 0 information and can't test this in the live game. Imo not worth trying to "fix" without risk of breaking parts of the server.

**Comment by ultraviolet-jordan** [comment]
Let's try getting the server in beta first?

**Comment by tannerdino** [comment]
I think it should definitely be implemented eventually. Pretty clear-cut proof that npc pathing was different during, and probably before, 2005. Can't call ourselves authentic with out it

I forgot to mention this in the main post but, in the 3rd video shown, the npc moves in a sort of zigzag pattern since the west wall is shaped like this (camera is facing west btw)
![image](https://github.com/user-attachments/assets/b8551bc8-3e93-452a-a834-427cdf4aff64)

**Comment by ultraviolet-jordan** [comment]
What if it only affected npcs larger than 1 tile? We have no idea. That's just 1 example of not enough information.

**Comment by tannerdino** [comment]
Thats a good theory. Went ahead and searched for more videos and found some examples, and I think you're right (see video 1)!! Also looks like the change was pinned down to be around September/October of 2005?

- Video 1, April 2005. Skeleton moves diagonally, and right after the scorpion moves cardinally! ([source](https://youtu.be/aI0uqOMkLQc?t=192)):

https://github.com/user-attachments/assets/8b7e6903-ee34-4e1c-a7db-2b004f49b5be

- Video 2, Sept 11, 2005. Big npc with cardinal pathing, at the top of the screen. ([source](https://youtu.be/6LoClg45lvA?t=94)):

https://github.com/user-attachments/assets/554ce1c5-868f-4e64-88ae-b76739ee3ed2

- Video 3, Oct 16, 2005. Big npc moving diagonally. ([source](https://youtu.be/QdWaq2RpyRU?t=11)):

https://github.com/user-attachments/assets/80efafd4-c1ca-4375-aee3-6f003b067412

**Comment by tannerdino** [comment]
My theory is that it big npcs were changed when fight caves were released. Its probably the biggest update between September 11 and October 16. The [blog post](https://oldschool.runescape.wiki/w/Update:TzHaar_Fight_Caves) for it dont seem to mention anything though unfortunately

**Comment by ultraviolet-jordan** [comment]
so wats da fix??

**Comment by ultraviolet-jordan** [comment]
Do it without naive pathfinder used is what it sounds like to me. Wandering and escape mode are very familiar to this.

**Comment by tannerdino** [comment]
This is probably authentic? idk if we'll ever find a video of this

https://github.com/user-attachments/assets/1644da16-36f7-45d5-b099-61e3914ab4be

**Comment by tannerdino** [comment]
Found a video from Aug 9, 2006 with big npc pathing! Perhaps big npc pathing was changed in 2006 with the npc graphical reworks? Video ([source](https://youtu.be/vLIp6qzwVMY?t=37)):


https://github.com/user-attachments/assets/d1346769-9a3b-4106-9801-b98343fd0913


 I think the video from 

> Video 3, Oct 16, 2005. Big npc moving diagonally.

Was just west movement + hit anim + south movement next tick.

**Comment by tannerdino** [comment]
Some more clips.

Sept 21, 2006 ([source](https://youtu.be/VRL-s772OgU?t=59)):


https://github.com/user-attachments/assets/31a1822f-2ccd-4664-829b-fab929a2fe93


Oct 7, 2006 ([source](https://youtu.be/oC_5EVw5fI0?t=39)):


https://github.com/user-attachments/assets/4094170c-f587-4477-adda-12c6aa4286f3
